server:
  name: bizserver
  http:
    addr: 0.0.0.0:8125
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9125
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  etcd:
    addr: localhost:2379
    username: root
    password: root
    timeout: 5s
  trace: 
    endpoint: 172.26.239.101:4318
    ratio: 1.0
    exporter: jaeger
